### PR TITLE
Sprint2 Integration test done, permission to merge to main branch

### PR DESCRIPTION
**Pull request by jasper-oh**

### CODE REVIEW

**Comment by jasper-oh** [comment]
Finished Integration Test. 
- Frontend layout done
- Backend prisma and query done.

**Comment by noelkim4924** [comment]
OMGILUVIT👊🏻

**Review by jchung7v — APPROVED** [review]
Great work. Please add your comments afterward 👍

**Comment by gdcho** [comment]
Integration test looks good to me!

**Pull request merged**
